// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATLR8Myc1mJZpqpGiJs2JdfpFJdOxJRrI',
    appId: '1:880094079813:web:f19f08a9d38629de2d2c2c',
    messagingSenderId: '880094079813',
    projectId: 'eunhee-final-nomadcoders',
    authDomain: 'eunhee-final-nomadcoders.firebaseapp.com',
    storageBucket: 'eunhee-final-nomadcoders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtz6Ulzgq71-SND6Hmz32Ns7LazFS_4k',
    appId: '1:880094079813:android:c06c038e1971c52d2d2c2c',
    messagingSenderId: '880094079813',
    projectId: 'eunhee-final-nomadcoders',
    storageBucket: 'eunhee-final-nomadcoders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzZ0C3oDwfdMhtm2FIxLl56eTse5LuVak',
    appId: '1:880094079813:ios:1847cf1dc19bc4d92d2c2c',
    messagingSenderId: '880094079813',
    projectId: 'eunhee-final-nomadcoders',
    storageBucket: 'eunhee-final-nomadcoders.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATLR8Myc1mJZpqpGiJs2JdfpFJdOxJRrI',
    appId: '1:880094079813:web:9a698211937b31772d2c2c',
    messagingSenderId: '880094079813',
    projectId: 'eunhee-final-nomadcoders',
    authDomain: 'eunhee-final-nomadcoders.firebaseapp.com',
    storageBucket: 'eunhee-final-nomadcoders.appspot.com',
  );
}
